<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" failures="1" tests="1" name="Login with Incorrect Credentials" time="13.379" errors="0" timestamp="7 Jul 2022 08:40:54 GMT">
  <testcase classname="nftTicketing.LoginIncorrectCredentials" name="LoginInvalidCredential" time="6.258">
    <failure type="java.lang.AssertionError" message="expected [User doesn&amp;apos;t exists] but found [User doesn&amp;apos;t exist]">
      <![CDATA[java.lang.AssertionError: expected [User doesn't exists] but found [User doesn't exist]
	at nftTicketing.LoginIncorrectCredentials.LoginInvalidCredential(LoginIncorrectCredentials.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginInvalidCredential -->
</testsuite> <!-- Login with Incorrect Credentials -->
